#!/usr/bin/env ruby

gem "activesupport"
gem "open-uri-cached"

$:.unshift(File.expand_path("../lib", __FILE__))

require "api"
require "generators"
require "helper"
require "inflections"

unless (1..3).include?(ARGV.size)
  puts "usage: #{$0} NAME [MODNAME] [URI]"
  exit 1
end

extend Helpers

api = API.new(*ARGV)

chdir api.name, "lib" do
  file api.file, Generators::Files::Main.new(api)

  chdir api.name do
    file "account.rb", Generators::Files::Account.new(api)
    file "errors.rb", Generators::Files::Errors.new(api)
    file "responses.rb", Generators::Files::Responses.new(api)
    file "types.rb", Generators::Files::Types.new(api)
  end
end

chdir "#{api.name}-cli" do
  chdir "bin" do
    file api.name, Generators::Files::CLI::Bin.new(api)
  end
  chdir "lib", api.name do
    file "cli.rb", Generators::Files::CLI::Main.new(api)
  end
end
