GEMS = %W[ebs ebs:cli ec2 ec2:cli elasticache elasticache:cli elb elb:cli r53 r53:cli rds rds:cli s3 s3:cli ses ses:cli]
DIRS = %W[ebs ebs-cli ec2 ec2-cli elasticache elasticache-cli elb elb-cli r53 r53-cli rds rds-cli s3 s3-cli ses ses-cli]

load "tasks/build.rake"
load "tasks/build/dependencies.rake"

namespace("aws") { load "../tasks/build.rake" }
namespace("aws:cli:base") { load "../aws-cli-base/tasks/build.rake" }
GEMS.zip(DIRS) do |name, dir|
  namespace(name) { load File.expand_path("../../#{dir}/tasks/build.rake", __FILE__) }
end
