load "tasks/build.rake"

namespace("aws") { load "../tasks/build.rake" }
namespace("aws:cli:base") { load "../aws-cli-base/tasks/build.rake" }
namespace("s3") { load "../s3/tasks/build.rake" }

task "aws:cli:base:build" => "aws:build"
task "aws:cli:base:install" => "aws:install"
task "s3:build" => "aws:build"
task "s3:install" => "aws:install"
task "build" => %w[aws:cli:base:build s3:build]
task "install" => %w[aws:cli:base:install s3:install]
