load "tasks/build.rake"

namespace("aws") { load "../tasks/build.rake" }
namespace("aws:cli:base") { load "../aws-cli-base/tasks/build.rake" }
namespace("ses") { load "../ses/tasks/build.rake" }

task "aws:cli:base:build" => "aws:build"
task "aws:cli:base:install" => "aws:install"
task "ses:build" => "aws:build"
task "ses:install" => "aws:install"
task "build" => %w[aws:cli:base:build ses:build]
task "install" => %w[aws:cli:base:install ses:install]
