load "tasks/build.rake"

namespace("aws") { load "../tasks/build.rake" }
namespace("aws:cli:base") { load "../aws-cli-base/tasks/build.rake" }
namespace("rds") { load "../rds/tasks/build.rake" }

task "aws:cli:base:build" => "aws:build"
task "aws:cli:base:install" => "aws:install"
task "rds:build" => "aws:build"
task "rds:install" => "aws:install"
task "build" => %w[aws:cli:base:build rds:build]
task "install" => %w[aws:cli:base:install rds:install]
