load "tasks/build.rake"

namespace("aws") { load "../tasks/build.rake" }
namespace("aws:cli:base") { load "../aws-cli-base/tasks/build.rake" }
namespace("elb") { load "../elb/tasks/build.rake" }

task "aws:cli:base:build" => "aws:build"
task "aws:cli:base:install" => "aws:install"
task "elb:build" => "aws:build"
task "elb:install" => "aws:install"
task "build" => %w[aws:cli:base:build elb:build]
task "install" => %w[aws:cli:base:install elb:install]
